/** @type {import('tailwindcss').Config} */
export default {
  darkMode: ["class"],
  content: ["./index.html", "./src/**/*.{ts,tsx,js,jsx}"],
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: { "2xl": "1400px" },
    },
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "#0B2E59",
          foreground: "#FFFFFF",
          50: "#EEF3FB",
          100: "#D5E1F5",
          200: "#ACC3EB",
          300: "#5887D8",
          400: "#2C5F9E",
          500: "#0B2E59",
          600: "#092549",
          700: "#071A2F",
          800: "#040F1A",
          900: "#020508",
        },
        secondary: {
          DEFAULT: "#A7CE39",
          foreground: "#1E293B",
          50: "#F4FAE6",
          100: "#E9F5CC",
          200: "#D3EC9A",
          300: "#BCE268",
          400: "#A7CE39",
          500: "#8FB52E",
          600: "#769124",
          700: "#556C1A",
          800: "#374710",
          900: "#192308",
        },
        accent: {
          DEFAULT: "#A7CE39",
          foreground: "#1E293B",
        },
        "dark-navy": "#071A2F",
        "sidebar-mid": "#0B2E59",
        "light-bg": "#F7F9FC",
        "card-bg": "#FFFFFF",
        "border-color": "#E2E8F0",
        "text-primary": "#1E293B",
        "text-secondary": "#64748B",
        success: "#22C55E",
        warning: "#F59E0B",
        danger: "#EF4444",
        destructive: {
          DEFAULT: "#EF4444",
          foreground: "#FFFFFF",
        },
        muted: {
          DEFAULT: "#F7F9FC",
          foreground: "#64748B",
        },
        popover: {
          DEFAULT: "#FFFFFF",
          foreground: "#1E293B",
        },
        card: {
          DEFAULT: "#FFFFFF",
          foreground: "#1E293B",
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      fontFamily: {
        sans: ["Inter", "system-ui", "sans-serif"],
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
        "fade-in": {
          from: { opacity: "0", transform: "translateY(8px)" },
          to: { opacity: "1", transform: "translateY(0)" },
        },
        "slide-in": {
          from: { transform: "translateX(-100%)" },
          to: { transform: "translateX(0)" },
        },
        "slide-up": {
          from: { opacity: "0", transform: "translateY(16px)" },
          to: { opacity: "1", transform: "translateY(0)" },
        },
        "scale-in": {
          from: { opacity: "0", transform: "scale(0.96)" },
          to: { opacity: "1", transform: "scale(1)" },
        },
        shimmer: {
          from: { backgroundPosition: "-200% 0" },
          to: { backgroundPosition: "200% 0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "fade-in": "fade-in 0.3s ease-out",
        "slide-in": "slide-in 0.3s ease-out",
        "slide-up": "slide-up 0.4s ease-out",
        "scale-in": "scale-in 0.2s ease-out",
        shimmer: "shimmer 2s infinite linear",
      },
      boxShadow: {
        card: "0 1px 3px 0 rgba(11, 46, 89, 0.07), 0 1px 2px -1px rgba(11, 46, 89, 0.05)",
        "card-hover": "0 8px 24px -4px rgba(11, 46, 89, 0.14), 0 2px 8px -2px rgba(11, 46, 89, 0.06)",
        sidebar: "4px 0 32px rgba(7, 26, 47, 0.25)",
        navbar: "0 1px 0 0 #E2E8F0",
        kpi: "0 2px 8px rgba(11, 46, 89, 0.08)",
        "kpi-hover": "0 10px 28px rgba(11, 46, 89, 0.16)",
        dropdown: "0 4px 24px -4px rgba(11, 46, 89, 0.16), 0 2px 8px -2px rgba(11, 46, 89, 0.08)",
        "input-focus": "0 0 0 3px rgba(167, 206, 57, 0.18)",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
};
