/** @type {import('tailwindcss').Config} */
export default {
  darkMode: ["class"],
  content: ["./index.html", "./src/**/*.{ts,tsx,js,jsx}"],
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: { "2xl": "1400px" },
    },
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "#1457E8",
          foreground: "#FFFFFF",
          50:  "#EBF1FF",
          100: "#D0E0FF",
          200: "#A2C0FF",
          300: "#6699FF",
          400: "#3D77F5",
          500: "#1457E8",
          600: "#0D43C0",
          700: "#09319A",
          800: "#052175",
          900: "#020F50",
        },
        secondary: {
          DEFAULT: "#00C882",
          foreground: "#022B1A",
          50:  "#E0FFF4",
          100: "#B8FFE4",
          200: "#73FFC9",
          300: "#25F5A5",
          400: "#00DE8F",
          500: "#00C882",
          600: "#00A46A",
          700: "#007C50",
          800: "#005436",
          900: "#002C1C",
        },
        accent: {
          DEFAULT: "#00C882",
          foreground: "#022B1A",
        },
        "dark-navy":    "#050D1F",
        "sidebar-mid":  "#0A1E4A",
        "light-bg":     "#F0F5FF",
        "card-bg":      "#FFFFFF",
        "border-color": "#D9E5FF",
        "text-primary":   "#0D1B3E",
        "text-secondary": "#5468A0",
        success:     "#00C882",
        warning:     "#F59E0B",
        danger:      "#EF4444",
        destructive: {
          DEFAULT: "#EF4444",
          foreground: "#FFFFFF",
        },
        muted: {
          DEFAULT: "#F0F5FF",
          foreground: "#5468A0",
        },
        popover: {
          DEFAULT: "#FFFFFF",
          foreground: "#0D1B3E",
        },
        card: {
          DEFAULT: "#FFFFFF",
          foreground: "#0D1B3E",
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      fontFamily: {
        sans: ["Inter", "system-ui", "sans-serif"],
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
        "fade-in": {
          from: { opacity: "0", transform: "translateY(8px)" },
          to: { opacity: "1", transform: "translateY(0)" },
        },
        "slide-in": {
          from: { transform: "translateX(-100%)" },
          to: { transform: "translateX(0)" },
        },
        "slide-up": {
          from: { opacity: "0", transform: "translateY(16px)" },
          to: { opacity: "1", transform: "translateY(0)" },
        },
        "scale-in": {
          from: { opacity: "0", transform: "scale(0.96)" },
          to: { opacity: "1", transform: "scale(1)" },
        },
        shimmer: {
          from: { backgroundPosition: "-200% 0" },
          to: { backgroundPosition: "200% 0" },
        },
        "pulse-glow": {
          "0%, 100%": { boxShadow: "0 0 0 0 rgba(20, 87, 232, 0)" },
          "50%": { boxShadow: "0 0 0 6px rgba(20, 87, 232, 0.15)" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up":   "accordion-up 0.2s ease-out",
        "fade-in":        "fade-in 0.3s ease-out",
        "slide-in":       "slide-in 0.3s ease-out",
        "slide-up":       "slide-up 0.4s ease-out",
        "scale-in":       "scale-in 0.2s ease-out",
        shimmer:          "shimmer 2s infinite linear",
        "pulse-glow":     "pulse-glow 2s ease-in-out infinite",
      },
      boxShadow: {
        card:        "0 1px 4px 0 rgba(20, 87, 232, 0.07), 0 1px 2px -1px rgba(20, 87, 232, 0.05)",
        "card-hover":"0 8px 28px -4px rgba(20, 87, 232, 0.18), 0 2px 8px -2px rgba(20, 87, 232, 0.08)",
        sidebar:     "4px 0 40px rgba(5, 13, 31, 0.35)",
        navbar:      "0 1px 0 0 #D9E5FF",
        kpi:         "0 2px 10px rgba(20, 87, 232, 0.10)",
        "kpi-hover": "0 10px 32px rgba(20, 87, 232, 0.22)",
        dropdown:    "0 4px 24px -4px rgba(20, 87, 232, 0.18), 0 2px 8px -2px rgba(20, 87, 232, 0.08)",
        "input-focus": "0 0 0 3px rgba(0, 200, 130, 0.22)",
        glow:        "0 0 20px rgba(20, 87, 232, 0.25)",
        "glow-green":"0 0 20px rgba(0, 200, 130, 0.30)",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
};
